<?php

namespace ContainerM9ZOadc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_76D1DH_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.76D1DH.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.76D1DH.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'addressRepository' => ['privates', 'App\\Repository\\AddressRepository', 'getAddressRepositoryService', true],
            'cart' => ['privates', 'App\\Classe\\Cart', 'getCartService', false],
        ], [
            'addressRepository' => 'App\\Repository\\AddressRepository',
            'cart' => 'App\\Classe\\Cart',
        ]);
    }
}
