<?php

namespace ContainerM9ZOadc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9Q9Fw1AService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9Q9Fw1A' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9Q9Fw1A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'headerRepository' => ['privates', 'App\\Repository\\HeaderRepository', 'getHeaderRepositoryService', true],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
        ], [
            'headerRepository' => 'App\\Repository\\HeaderRepository',
            'productRepository' => 'App\\Repository\\ProductRepository',
        ]);
    }
}
