<?php

namespace ContainerM9ZOadc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddressRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\AddressRepository' shared autowired service.
     *
     * @return \App\Repository\AddressRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'AddressRepository.php';

        return $container->privates['App\\Repository\\AddressRepository'] = new \App\Repository\AddressRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
