<?php

namespace ContainerX1Uhwkx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarrierRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\CarrierRepository' shared autowired service.
     *
     * @return \App\Repository\CarrierRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'CarrierRepository.php';

        return $container->privates['App\\Repository\\CarrierRepository'] = new \App\Repository\CarrierRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
