<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX1Uhwkx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX1Uhwkx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX1Uhwkx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX1Uhwkx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX1Uhwkx\App_KernelDevDebugContainer([
    'container.build_hash' => 'X1Uhwkx',
    'container.build_id' => 'deb7f815',
    'container.build_time' => 1712071257,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX1Uhwkx');
